server:
  port: 8002
spring:
  application:
    name: oms-provider-adv
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.0.99.68:3306/fznews_adv?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX 
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      filter:
        stat:
          enabled: false
mybatis:
  type-aliases-package: com.lt.cloud.pojo
  mapper-locations:
  - classpath:mapper/*.xml

logging:
  level:
     org.springframework.orm.jpa: debug  #输出查询语句
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    hystrix:
      config:
        hystrix.command.default.execution.isolation.strategy: SEMAPHORE
        hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 20  # 发呆时间，即服务续约到期时间（缺省为90s）  
# To set thread isolation to SEMAPHORE for LCN        
#txmanager地址
tm: 
  manager:
    url: http://localhost:7000/tx/manager/
    serviceId: TX-MANAGER
    
      
     