version: "3"
services:
  rabbit:
    image: rabbitmq:management
    hostname: rabbitmq
    ports: 
      - "15672:15672"
  microservice-discovery-eureka: 
    image: registry.cn-hangzhou.aliyuncs.com/mumushuiding/microservice-discovery-eureka:0.0.1-SNAPSHOT
    deploy: 
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    ports: 
      - "8761:8761"
    hostname: eureka-server
  microservice-config-server: 
    image: registry.cn-hangzhou.aliyuncs.com/mumushuiding/microservice-config-server-refresh-bus:0.0.1-SNAPSHOT  
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    ports:
    - "8888:8888"
    hostname: microservice-config-server
    depends_on: 
      - rabbit
    links: 
      - "microservice-discovery-eureka:eureka-server"
      - rabbit:rabbitmq
