server:
  port: 7999
spring:
  application:
      name: oms-gataway-zuul
  resources: 
    chain:
      cache: false
      gzipped: true
    cache:
      period: 604800  
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    hystrix:
      config:
        hystrix.command.default.execution.isolation.strategy: SEMAPHORE
        hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true
# To set thread isolation to SEMAPHORE for LCN 
init-db: true
hystrix:
  command: 
    default:
      execution:
        isolation:
          strategy: SEMAPHORE 
#txmanager地址
tm: 
  manager:
    url: http://${TX_MANAGER_ADDRESS}:7000/tx/manager/
    
    