server:
  port: 8004
spring:
  application:
    name: oms-provider-public
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.0.99.68:3306/fznews_public?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX 
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          enabled: false
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 20  # 发呆时间，即服务续约到期时间（缺省为90s）
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"