profile: oms-provider-zuul
logging:
  level:
     com.lt.cloud.mapper: debug  #输出查询语句
zuul:
  add-host-header: true
eureka: 
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 20  # 发呆时间，即服务续约到期时间（缺省为90s）
