profile: oms-provider-public
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.0.99.68:3306/fznews_public?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX 
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          enabled: false
logging:
  level:
     com.lt.cloud.mapper: debug  #输出查询语句
eureka: 
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 20  # 发呆时间，即服务续约到期时间（缺省为90s）
