spring: 
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mumushuiding/spring-cloud-config     # 配置Git仓库的地址
          username:                                        # Git仓库的账号
          password:   
    bus:
      trace:
        enabled: true
  

